-- CREACIÓN DE BASE DE DATOS PERSONALIZADO
CREATE DATABASE BD_NEGOCIO_RAMOS
ON
(NAME='NEGOC_Data',
FILENAME='G:\Exam\NEGOC_Data.MDF',
SIZE=8MB, MAXSIZE=500MB, FILEGROWTH=20MB)
LOG ON -- (<-- AGREGA PRIMARY AUTOMÁTICAMENTE)
(NAME='NEGOC_Log',
FILENAME='G:\Exam\NEGOC_Log.LDF',
SIZE=8MB, MAXSIZE=50MB, FILEGROWTH=30%);
GO

-- AGREGAMOS 3 GRUPOS DE ARCHIVOS PARA PODER INSERTAR ARCHIVOS NDF
ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILEGROUP GRUPO1;
ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILEGROUP GRUPO2;
ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILEGROUP GRUPO3;
GO

-- ©RONNY CHICLLA ZAMORA

-- AGREGAMOS ARCHIVOS SECUNDARIOS NDF
ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILE (
NAME = NEGOC_DataSec1,
FILENAME = 'G:\Evaluacion\NEGOC_DataSec1.NDF', -- (<-- ARCHIVO NDF)
SIZE = 1MB, MAXSIZE = 20MB, FILEGROWTH = 1MB)
TO FILEGROUP GRUPO1;
GO

ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILE (
NAME = NEGOC_DataSec2,
FILENAME = 'G:\Evaluacion\NEGOC_DataSec2.NDF', -- (<-- ARCHIVO NDF)
SIZE = 2MB, MAXSIZE = 25MB, FILEGROWTH = 2MB)
TO FILEGROUP GRUPO2;
GO

ALTER DATABASE BD_NEGOCIO_RAMOS ADD FILE (
NAME = NEGOC_DataSec3,
FILENAME = 'G:\Evaluacion\NEGOC_DataSec3.NDF', -- (<-- ARCHIVO NDF)
SIZE = 3MB, MAXSIZE = 30MB, FILEGROWTH = 3MB)
TO FILEGROUP GRUPO3;